name: DutchyTPA
main: dev.array21.dutchytpa.Tpa
version: 1.2.0
api-version: 1.16
author: TobiasDeBruijn
description: A simple TPA plugin
commands:
 tpa:
  description: TPA to a player
 tpaccept:
  description: Accept a TPA request
 tpdeny:
  description: Deny a TPA request
 tpyes:
  description: Alias for /tpaccept
 tpno:
  description: Alias for /tpdeny
permissions:
 tpa.deny:
  description: "Allows the use of the /tpdeny command"
  default: true
 tpa.accept:
  description: "Allows the use of the /tpaccept command"
  default: true
 tpa.tpa:
  description: "Allows the use of the /tpa command"
  default: true